### PR TITLE
Remove rosunit recommendation

### PR DESCRIPTION
**Pull request by bmagyar**
Following the findings of https://github.com/ros-controls/ros_control/issues/408, I've updated the cmake hooks

### CODE REVIEW

**Comment by bmagyar** [comment]
@dirk-thomas, could you please advise us on this one?

**Comment by dirk-thomas** [comment]
`catkin` itself doesn't need / use `rosunit`. The CMake functions containing `rostest` in the name are provided by the `rostest` package and that package depends on `rosunit`. But if a package depends on `rostest` it doesn't need to declare a dependency on `rosunit` (except if it explicitly uses it somewhere directly).

**Comment by ipa-mdl** [comment]
@dirk-thomas: Is https://github.com/ros/catkin/blob/kinetic-devel/doc/howto/format2/gtest_configuration.rst out-of-date?

**Comment by dirk-thomas** [comment]
That could be. Or we are missing a reason why it is still needed.

**Pull request merged**
